### ISSUE TITLE
Remove Part Files as Added?

### ISSUE THREAD

**Issue by arrmo** [BrettSheleski/comchap#16]
Hi,

Just a thought, as it saves needed disk space - but after a part-xx.ts file is added ... remove it? If not about 3x the disk space is needed overall (the original file, the part files, and then the cut file).

Thoughts?

Thanks!

**Comment by BrettSheleski** [comment]
All part files are combined at once. 

Alternatively a new file containing just the parts to keep could be done in sort of a "running total" file. As I think of it, that would actually result in needing an additional temporary file and thus additional storage.

I don't know of any good way of reducing storage requirements

**Comment by BrettSheleski** [comment]
I should add that both comcut and comchap will replace the source file if no output file is specified. Not specifying an output file would only require 2x the storage

**Comment by arrmo** [comment]
No worries, just wasn't sure if they were added sequentially or not - sounds like not. Thanks!
