### ISSUE TITLE
comcut output file is huge

### ISSUE THREAD

**Issue by andlo** [BrettSheleski/comchap#22]
I try to cut com's from an .ts file, but the output is much bigger than inputfile

Why is that, and anyway to change that ?

**Comment by BrettSheleski** [comment]
Strange. It should be keeping the the source encoding for both the audio and video, so I don't see a reason why this would be happening.

**Comment by andlo** [comment]
yah strange - maybe my test files weresick.

It looks like it works on newly recorded movies :)
