### ISSUE TITLE
Strange issue with ffmpeg not successfully adding chapters

### ISSUE THREAD

**Issue by Reed97123** [BrettSheleski/comchap#36]
This has been working for me for well over a year now, but suddenly chapters are not being added by ffmpeg.  The edl file is created just fine.  The meta file is created for ffmpeg.  Ffmpeg runs without any error, but the chapters are just not present.  I'm at a loss because I haven't changed anything on my system, so I have no idea what update might have broken it.

**Comment by iwikus** [comment]
I found this issue when trying to get comchap work. Should ffprobe -show_chapters test.ts display chapters merged to stream using comchap? I can not see any. 
EDIT: Maybe this is answer?
_"The containers MPG/VOB and TS/M2TS don't have a global header and don't support chapter marks either. Transport streams were created for broadcasting"_

**Comment by BrettSheleski** [comment]
Well that appears to be your answer.  To resolve this I would save the resulting file to a supported container (mkv/mp4).  

You can do this with something like
```
comchap inputfile.ts outputfile.mp4
```

This will cause ffmpeg to create an MP4 file from your input.

**Comment by Reed97123** [comment]
How about in my case?  I haven't touched any of the software components in over half a year.  Just one day it was working and then the next it wasn't.  I hadn't been changing any settings recently, it just up and stopped working one day.  

Any ideas on how to debug this when the input file to ffmpeg looks good and it gives no errors, but it doesn't add chapters?  I'm really not sure where to look next.

**Comment by BrettSheleski** [comment]
I don't have enough information for your case.  I'd have to see what's failing and why.  Seeing as you had it working in the past, I assume you're going to proper formats that support chapters.  I'd start by preserving the ffmeta file and see its contents.

**Comment by Reed97123** [comment]
Here's two edl from SUCCESSFUL runs:

0.00	8.07	0
603.00	771.40	0
1265.63	1437.87	0
2052.38	2344.54	0
2663.86	2967.26	0
3490.95	3599.10	0

0.00	8.94	0
870.70	1046.81	0
1637.44	1800.03	0
2256.82	2547.95	0
2975.34	3277.91	0
3492.92	3599.53	0

And one from where it was UNSUCCESSFUL:
607.67	769.94	0
2144.48	2267.87	0
2813.11	3107.54	0
3492.36	3598.46	0

SUCCESSFUL FFMETA:
;FFMETADATA1
[CHAPTER]
TIMEBASE=1/1000
START=0
END=0
title=Chapter 1
[CHAPTER]
TIMEBASE=1/1000
START=0
END=8070
title=Commercial 1
[CHAPTER]
TIMEBASE=1/1000
START=8070
END=603000
title=Chapter 2
[CHAPTER]
TIMEBASE=1/1000
START=603000
END=771400
title=Commercial 2
[CHAPTER]
TIMEBASE=1/1000
START=771400
END=1265630
title=Chapter 3
[CHAPTER]
TIMEBASE=1/1000
START=1265630
END=1437870
title=Commercial 3
[CHAPTER]
TIMEBASE=1/1000
START=1437870
END=2052380
title=Chapter 4
[CHAPTER]
TIMEBASE=1/1000
START=2052380
END=2344540
title=Commercial 4
[CHAPTER]
TIMEBASE=1/1000
START=2344540
END=2663860
title=Chapter 5
[CHAPTER]
TIMEBASE=1/1000
START=2663860
END=2967260
title=Commercial 5
[CHAPTER]
TIMEBASE=1/1000
START=2967260
END=3490950
title=Chapter 6
[CHAPTER]
TIMEBASE=1/1000
START=3490950
END=3599100
title=Commercial 6
[CHAPTER]
TIMEBASE=1/1000
START=3599100
END=3599370
title=Chapter 7

UNSUCCESSFUL FFMETA:
;FFMETADATA1
[CHAPTER]
TIMEBASE=1/1000
START=0
END=607670
title=Chapter 1
[CHAPTER]
TIMEBASE=1/1000
START=607670
END=769940
title=Commercial 1
[CHAPTER]
TIMEBASE=1/1000
START=769940
END=2144480
title=Chapter 2
[CHAPTER]
TIMEBASE=1/1000
START=2144480
END=2267870
title=Commercial 2
[CHAPTER]
TIMEBASE=1/1000
START=2267870
END=2813110
title=Chapter 3
[CHAPTER]
TIMEBASE=1/1000
START=2813110
END=3107540
title=Commercial 3
[CHAPTER]
TIMEBASE=1/1000
START=3107540
END=3492360
title=Chapter 4
[CHAPTER]
TIMEBASE=1/1000
START=3492360
END=3598460
title=Commercial 4
[CHAPTER]
TIMEBASE=1/1000
START=3598460
END=3598730
title=Chapter 5

**Comment by Reed97123** [comment]
I've noticed a couple of things that are leading me towards some conclusions.  I noticed that on the files that did work started at time 0.

I also saw that VLC was able to find the chapters in all the files.  I had been only using Plex's player so far to gauge whether they had chapters.  I tried to double-confirm with "ffprobe -show_chapters <file>" but I got an error back that "show_chapters" was an unknown option.

So my working theory is that comskip is somehow detecting things differently, the chapters are actually there, but for some reason Plex can't find the slightly altered format.

**Comment by BrettSheleski** [comment]
> I also saw that VLC was able to find the chapters in all the files.

This sounds like it's may be an issue with Plex not comchap.

**Comment by Reed97123** [comment]
I'd have to agree.  I have the ffprobe -show_chapters  <file> working and it double confirms.  Strange, I'll follow-up with Plex.  Thanks for helping bounce ideas.

**Comment by jwrober** [comment]
> I found this issue when trying to get comchap work. Should ffprobe -show_chapters test.ts display chapters merged to stream using comchap? I can not see any.
> EDIT: Maybe this is answer?
> _"The containers MPG/VOB and TS/M2TS don't have a global header and don't support chapter marks either. Transport streams were created for broadcasting"_

Would it be possible to alter the script to see if the $infile ends in .ts or .vob or something and automatically output to .mp4?

**Comment by Reed97123** [comment]
My issue was root caused to Plex not seeing the chapters, temporarily.
They fixed it.

I don't have any current outstanding issues.

**Comment by BrettSheleski** [comment]
@jwrober, I'm not altering the script to do any sort of automatic detection of input and forcing to any specific format (mp4 included). If you want an mp4 output file then specify the output filename that you want. Write a simple wrapper script if you need to.
