### ISSUE TITLE
Anyplans to make a windows version?

### ISSUE THREAD

**Issue by Yankees4life** [BrettSheleski/comchap#47]
Hello

Is there any plans to make a windows version? I would like to use this with WMC.

**Comment by BrettSheleski** [comment]
You might be able to have some luck with Windows Subsystem for Linux (WSL).

**Comment by Yankees4life** [comment]
That would be a bit of a wonky setup instead of touch and go. I'm gonna try mess around with Dirmon2 and a batch file with comskip and mencoder if see that'll work. 

Thanks for the work

**Comment by BrettSheleski** [comment]
It probably wouldn't be too terribly difficult to write a batch script and/or PowerShell script version of comchap/comcut for Windows. If one were to do so I may even include it in this repo.

**Comment by Yankees4life** [comment]
> It probably wouldn't be too terribly difficult to write a batch script and/or PowerShell script version of comchap/comcut for Windows. If one were to do so I may even include it in this repo.

Without a source code, that would be tough for me (and others maybe).

**Comment by BrettSheleski** [comment]
Comchap/comcut are simple scripts really. The source is right here on GitHub. The only real dependents are ComSkip and ffmpeg, both of which have windows versions. Go nuts.

**Comment by Yankees4life** [comment]
> Comchap/comcut are simple scripts really. The source is right here on GitHub. The only real dependents are ComSkip and ffmpeg, both of which have windows versions. Go nuts.

So the challenge would be to convert a linux script into a bat file. Hmm...🤔

Let's see what I can do

**Comment by Yankees4life** [comment]
Well...4 months later...and I have just developed a script for windows using the ffsplit files that comskip can generate. I use a for script using bat (a windows fork of cat) to pass the commands on that file onto ffmpeg and then use fd to echo the segment files onto a txt file so that ffmpeg can combine it back into one. Simple right. Give it a whirl here. I hope this works as an alternative to MCEBuddy on that platform
https://github.com/Yankees4life/comcutter

**Comment by BrettSheleski** [comment]
Nice. Good luck with your implementation.

I thought about doing an implementation in python to be more cross platform compatible. However that would mean an added dependency on Python.  A docker image would be cool too...

**Comment by Yankees4life** [comment]
I have returned and I've seen that somebody has finally created a windows version in this repo too so I'm closing this baby out.
